### ISSUE TITLE
Pagina is te lang als het menu niet open staat.

### ISSUE THREAD

**Issue by JathoSystems** [JathoSystems/WEBS1#3]
Ik weet niet hoe ik dit moet oplossen op een manier dat de transition nog blijft werken.
Maar het doet nu een beetje jammer met de footer als het menu niet openstaat.
![2022-09-16 12_42_06-Document - Vivaldi](https://user-images.githubusercontent.com/71022949/190621634-94d14257-721c-43ba-9458-17dfe4398a02.png)

**Comment by JesperIV** [comment]
Wanneer gebeurt dit? Ik ben aan het testen maar ik krijg het probleem niet

**Comment by JathoSystems** [comment]
Wanneer de viewport heel laag is, is niet het grootste probleem maarja.
Ik zit te denken de transitie wat korter te maken.
Andere oplossing zou zijn om gewoon alle pagina's genoeg content te laten hebben.

**Comment by JathoSystems** [comment]
Ik kan niet nadenken trouwens ik bedoel een viewport met een lage waarde,
Dus neem 1080 bij 400 bijvoorbeeld.

**Comment by JathoSystems** [comment]
Ik ga de animatie gewoon van boven laten komen, bespaart heel veel moeite denk ik.
